
import React from 'react';
import { ProcessingResult } from '../types';

interface DocumentPreviewProps {
  result: ProcessingResult;
}

const DocumentPreview: React.FC<DocumentPreviewProps> = ({ result }) => {
  const isOriginalPdf = result.content === "DOCUMENT_ORIGINAL_PDF";

  return (
    <div className="bg-white shadow-2xl rounded-xl overflow-hidden border border-slate-200 animate-in fade-in slide-in-from-bottom-4 duration-700">
      <div className="bg-slate-50 border-b border-slate-200 p-4 flex justify-between items-center no-print">
        <div className="flex space-x-2">
          <div className="w-3 h-3 rounded-full bg-red-400"></div>
          <div className="w-3 h-3 rounded-full bg-yellow-400"></div>
          <div className="w-3 h-3 rounded-full bg-green-400"></div>
        </div>
        <span className="text-xs font-medium text-slate-400 uppercase tracking-widest">
            {isOriginalPdf ? 'Original Document (Fast-Pass)' : 'AI-Enhanced Document'}
        </span>
      </div>
      
      <div className="p-8 md:p-16 bg-white print-area min-h-[842px] max-w-4xl mx-auto overflow-auto">
        <div className="mb-12 border-b border-indigo-100 pb-8">
            <h1 className="text-4xl font-bold text-slate-900 mb-4">{result.title}</h1>
            <div className="flex flex-wrap gap-2 mb-6">
                {result.tags.map(tag => (
                    <span key={tag} className={`px-3 py-1 text-xs font-semibold rounded-full uppercase ${tag === 'Original' ? 'bg-emerald-50 text-emerald-600' : 'bg-indigo-50 text-indigo-600'}`}>
                        {tag}
                    </span>
                ))}
            </div>
            <div className={`p-4 rounded-lg border-l-4 italic text-sm no-print ${isOriginalPdf ? 'bg-emerald-50 border-emerald-500 text-emerald-700' : 'bg-slate-50 border-indigo-500 text-slate-600'}`}>
                <strong>Status:</strong> {result.summary}
            </div>
        </div>

        {isOriginalPdf ? (
            <div className="flex flex-col items-center justify-center py-20 bg-slate-50/50 rounded-2xl border-2 border-dashed border-slate-200">
                <svg className="w-20 h-20 text-emerald-500 mb-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                </svg>
                <h2 className="text-2xl font-black text-slate-800 mb-2">Fichier PDF Prêt</h2>
                <p className="text-slate-500 text-center max-w-sm">Ce document a été validé et est prêt pour l'exportation directe sans modification.</p>
            </div>
        ) : (
            <div className="prose prose-indigo max-w-none text-slate-700 leading-relaxed">
              {result.content.split('\n').map((line, i) => {
                  if (line.startsWith('# ')) return <h1 key={i} className="text-3xl font-bold mt-8 mb-4">{line.replace('# ', '')}</h1>;
                  if (line.startsWith('## ')) return <h2 key={i} className="text-2xl font-bold mt-6 mb-3 border-b pb-2">{line.replace('## ', '')}</h2>;
                  if (line.startsWith('### ')) return <h3 key={i} className="text-xl font-bold mt-5 mb-2">{line.replace('### ', '')}</h3>;
                  if (line.trim() === '') return <div key={i} className="h-4"></div>;
                  return <p key={i} className="mb-4">{line}</p>;
              })}
            </div>
        )}

        <div className="mt-20 pt-8 border-t border-slate-100 flex justify-between text-[10px] text-slate-400 uppercase tracking-widest">
            <span>Generated by OmniPDF AI Ultra</span>
            <span>{new Date().toLocaleDateString()}</span>
            <span>Confidential & Original</span>
        </div>
      </div>
    </div>
  );
};

export default DocumentPreview;
